output: build
exclude:
  - _attic
packages:
  - name: mod_tuning.package
    files:
      - src/tuning/**/*
strings:
  - name: mod_strings.package
    files:
      - src/strings/**/*
merges:
  - name: Astonisher_Mod.package
    combineStrings: true
    files:
      - build/mod_strings.package
      - build/mod_tuning.package
      - include/astonisher_statue.package
      - include/astonisher2_statue.package
