output: build
exclude:
  - _attic
packages:
  - name: test_tuning.package
    files:
      - src/tuning/**/*
strings:
  - name: strings_package.package
    files:
      #      - src/220557DA!80000000!0000000099C531AC.properties
      - src/strings/**/*
merges:
  - name: Astonisher_Mod.package
    combineStrings: false
    files:
      - build/strings_package.package
      - build/test_tuning.package
      - include/astonisher_statue.package
      - include/astonisher2_statue.package
