output: build
exclude:
  - _attic
packages:
  - name: test_tuning.package
    files:
      - src/**/*
strings:
      - name: strings_tuning.package
        files:
          - src/220557DA!80000000!0000000099C531AC.properties
